insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('MXN', 'Peso');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('UAH', 'Hryvnia');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('VEF', 'Bolivar');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('AZN', 'Manat');
insert into raw_currency_tab (currency, description) values ('CUP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('IRR', 'Rial');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('JMD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('AFN', 'Afghani');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('SYP', 'Pound');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('VND', 'Dong');
insert into raw_currency_tab (currency, description) values ('HRK', 'Kuna');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('UZS', 'Som');
insert into raw_currency_tab (currency, description) values ('COP', 'Peso');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('HRK', 'Kuna');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('XCD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('TZS', 'Shilling');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('AMD', 'Dram');
insert into raw_currency_tab (currency, description) values ('COP', 'Peso');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('MGA', 'Ariary');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('XAF', 'Franc');
insert into raw_currency_tab (currency, description) values ('XOF', 'Franc');
insert into raw_currency_tab (currency, description) values ('PKR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('MUR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('XOF', 'Franc');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('HNL', 'Lempira');
insert into raw_currency_tab (currency, description) values ('YER', 'Rial');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('UAH', 'Hryvnia');
insert into raw_currency_tab (currency, description) values ('LBP', 'Pound');
insert into raw_currency_tab (currency, description) values ('MNT', 'Tugrik');
insert into raw_currency_tab (currency, description) values ('XAF', 'Franc');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('GTQ', 'Quetzal');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('COP', 'Peso');
insert into raw_currency_tab (currency, description) values ('AFN', 'Afghani');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('AFN', 'Afghani');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('TMT', 'Manat');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('AUD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('GYD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CAD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('CAD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('BDT', 'Taka');
insert into raw_currency_tab (currency, description) values ('BYR', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('MRO', 'Ouguiya');
insert into raw_currency_tab (currency, description) values ('LKR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('DKK', 'Krone');
insert into raw_currency_tab (currency, description) values ('GTQ', 'Quetzal');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('HTG', 'Gourde');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('MYR', 'Ringgit');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('ALL', 'Lek');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('KZT', 'Tenge');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('ZAR', 'Rand');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('SYP', 'Pound');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('SZL', 'Lilangeni');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('GEL', 'Lari');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('SAR', 'Rial');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('VND', 'Dong');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('DOP', 'Peso');
insert into raw_currency_tab (currency, description) values ('ALL', 'Lek');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('BGN', 'Lev');
insert into raw_currency_tab (currency, description) values ('BAM', 'Marka');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('ETB', 'Birr');
insert into raw_currency_tab (currency, description) values ('KWD', 'Dinar');
insert into raw_currency_tab (currency, description) values ('CLP', 'Peso');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CAD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('AFN', 'Afghani');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('KZT', 'Tenge');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('HNL', 'Lempira');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('VND', 'Dong');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('KRW', 'Won');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('KRW', 'Won');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('XOF', 'Franc');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('XPF', 'Franc');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('HTG', 'Gourde');
insert into raw_currency_tab (currency, description) values ('MNT', 'Tugrik');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('GTQ', 'Quetzal');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('NOK', 'Krone');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('COP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('AFN', 'Afghani');
insert into raw_currency_tab (currency, description) values ('MXN', 'Peso');
insert into raw_currency_tab (currency, description) values ('CAD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('BAM', 'Marka');
insert into raw_currency_tab (currency, description) values ('PKR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('KMF', 'Franc');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('HUF', 'Forint');
insert into raw_currency_tab (currency, description) values ('YER', 'Rial');
insert into raw_currency_tab (currency, description) values ('AUD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('BDT', 'Taka');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('EGP', 'Pound');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('PKR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('HRK', 'Kuna');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('GTQ', 'Quetzal');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('YER', 'Rial');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('COP', 'Peso');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('MNT', 'Tugrik');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('PKR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('CLP', 'Peso');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('SYP', 'Pound');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('GNF', 'Franc');
insert into raw_currency_tab (currency, description) values ('BOB', 'Boliviano');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('UAH', 'Hryvnia');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('ZMW', 'Kwacha');
insert into raw_currency_tab (currency, description) values ('COP', 'Peso');
insert into raw_currency_tab (currency, description) values ('ZAR', 'Rand');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('UAH', 'Hryvnia');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('MXN', 'Peso');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('NOK', 'Krone');
insert into raw_currency_tab (currency, description) values ('KRW', 'Won');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('COP', 'Peso');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('KZT', 'Tenge');
insert into raw_currency_tab (currency, description) values ('UYU', 'Peso');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('MAD', 'Dirham');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('PAB', 'Balboa');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('DKK', 'Krone');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('BHD', 'Dinar');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('HNL', 'Lempira');
insert into raw_currency_tab (currency, description) values ('NZD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('UGX', 'Shilling');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('GTQ', 'Quetzal');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('LTL', 'Litas');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('AFN', 'Afghani');
insert into raw_currency_tab (currency, description) values ('AZN', 'Manat');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('KPW', 'Won');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('VND', 'Dong');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('AMD', 'Dram');
insert into raw_currency_tab (currency, description) values ('BOB', 'Boliviano');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('HNL', 'Lempira');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('MXN', 'Peso');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('LKR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('HRK', 'Kuna');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('MYR', 'Ringgit');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('RSD', 'Dinar');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('XOF', 'Franc');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('KZT', 'Tenge');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CUP', 'Peso');
insert into raw_currency_tab (currency, description) values ('VEF', 'Bolivar');
insert into raw_currency_tab (currency, description) values ('PAB', 'Balboa');
insert into raw_currency_tab (currency, description) values ('ALL', 'Lek');
insert into raw_currency_tab (currency, description) values ('GBP', 'Pound');
insert into raw_currency_tab (currency, description) values ('NOK', 'Krone');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('HRK', 'Kuna');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('MNT', 'Tugrik');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('XAF', 'Franc');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CUP', 'Peso');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('BOB', 'Boliviano');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('ILS', 'Shekel');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('COP', 'Peso');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('GTQ', 'Quetzal');
insert into raw_currency_tab (currency, description) values ('CUP', 'Peso');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('YER', 'Rial');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('MAD', 'Dirham');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('CAD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('HKD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('XOF', 'Franc');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('GYD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('MKD', 'Denar');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('BIF', 'Franc');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('IRR', 'Rial');
insert into raw_currency_tab (currency, description) values ('TND', 'Dinar');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CRC', 'Colon');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('GHS', 'Cedi');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('PKR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('XOF', 'Franc');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('BWP', 'Pula');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('XOF', 'Franc');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('LAK', 'Kip');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('TND', 'Dinar');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('MXN', 'Peso');
insert into raw_currency_tab (currency, description) values ('IQD', 'Dinar');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('KES', 'Shilling');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('BYR', 'Ruble');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('MAD', 'Dirham');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('KRW', 'Won');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('BAM', 'Marka');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('SYP', 'Pound');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('VND', 'Dong');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('NPR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('NPR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PKR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('BAM', 'Marka');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('KRW', 'Won');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('AZN', 'Manat');
insert into raw_currency_tab (currency, description) values ('SYP', 'Pound');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('COP', 'Peso');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('ETB', 'Birr');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('RSD', 'Dinar');
insert into raw_currency_tab (currency, description) values ('HRK', 'Kuna');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('MYR', 'Ringgit');
insert into raw_currency_tab (currency, description) values ('BOB', 'Boliviano');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('MKD', 'Denar');
insert into raw_currency_tab (currency, description) values ('SYP', 'Pound');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('VEF', 'Bolivar');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('HRK', 'Kuna');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('HUF', 'Forint');
insert into raw_currency_tab (currency, description) values ('PKR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('ZMW', 'Kwacha');
insert into raw_currency_tab (currency, description) values ('MXN', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('HRK', 'Kuna');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('PKR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('EGP', 'Pound');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('AZN', 'Manat');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('BYR', 'Ruble');
insert into raw_currency_tab (currency, description) values ('RSD', 'Dinar');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('KRW', 'Won');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('MDL', 'Leu');
insert into raw_currency_tab (currency, description) values ('HNL', 'Lempira');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('UYU', 'Peso');
insert into raw_currency_tab (currency, description) values ('ALL', 'Lek');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('KHR', 'Riels');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('PAB', 'Balboa');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('VND', 'Dong');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('MYR', 'Ringgit');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('AFN', 'Afghani');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('MNT', 'Tugrik');
insert into raw_currency_tab (currency, description) values ('VND', 'Dong');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('NIO', 'Cordoba');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('MKD', 'Denar');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('BYR', 'Ruble');
insert into raw_currency_tab (currency, description) values ('GTQ', 'Quetzal');
insert into raw_currency_tab (currency, description) values ('KES', 'Shilling');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('UAH', 'Hryvnia');
insert into raw_currency_tab (currency, description) values ('XAF', 'Franc');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('AFN', 'Afghani');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('KZT', 'Tenge');
insert into raw_currency_tab (currency, description) values ('PAB', 'Balboa');
insert into raw_currency_tab (currency, description) values ('MXN', 'Peso');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('MRO', 'Ouguiya');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('COP', 'Peso');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('CLP', 'Peso');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('RSD', 'Dinar');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('MXN', 'Peso');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('NOK', 'Krone');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('DKK', 'Krone');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('SDG', 'Pound');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('UAH', 'Hryvnia');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('AOA', 'Kwanza');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('USD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('KGS', 'Som');
insert into raw_currency_tab (currency, description) values ('SZL', 'Lilangeni');
insert into raw_currency_tab (currency, description) values ('PEN', 'Sol');
insert into raw_currency_tab (currency, description) values ('MUR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('HRK', 'Kuna');
insert into raw_currency_tab (currency, description) values ('VND', 'Dong');
insert into raw_currency_tab (currency, description) values ('COP', 'Peso');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('HNL', 'Lempira');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('JOD', 'Dinar');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('GNF', 'Franc');
insert into raw_currency_tab (currency, description) values ('UAH', 'Hryvnia');
insert into raw_currency_tab (currency, description) values ('BYR', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CDF', 'Franc');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('UAH', 'Hryvnia');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('UAH', 'Hryvnia');
insert into raw_currency_tab (currency, description) values ('ZMW', 'Kwacha');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('MKD', 'Denar');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('IRR', 'Rial');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('GTQ', 'Quetzal');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PKR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('UAH', 'Hryvnia');
insert into raw_currency_tab (currency, description) values ('CAD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('MKD', 'Denar');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('AMD', 'Dram');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('KRW', 'Won');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CUP', 'Peso');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('SEK', 'Krona');
insert into raw_currency_tab (currency, description) values ('KES', 'Shilling');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('LYD', 'Dinar');
insert into raw_currency_tab (currency, description) values ('VEF', 'Bolivar');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('BYR', 'Ruble');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('TND', 'Dinar');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('CAD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('KPW', 'Won');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('MZN', 'Metical');
insert into raw_currency_tab (currency, description) values ('VND', 'Dong');
insert into raw_currency_tab (currency, description) values ('PYG', 'Guarani');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('HRK', 'Kuna');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('CAD', 'Dollar');
insert into raw_currency_tab (currency, description) values ('VEF', 'Bolivar');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('BRL', 'Real');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('JPY', 'Yen');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('EUR', 'Euro');
insert into raw_currency_tab (currency, description) values ('CZK', 'Koruna');
insert into raw_currency_tab (currency, description) values ('LKR', 'Rupee');
insert into raw_currency_tab (currency, description) values ('THB', 'Baht');
insert into raw_currency_tab (currency, description) values ('EGP', 'Pound');
insert into raw_currency_tab (currency, description) values ('PHP', 'Peso');
insert into raw_currency_tab (currency, description) values ('PLN', 'Zloty');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('ARS', 'Peso');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('NGN', 'Naira');
insert into raw_currency_tab (currency, description) values ('IDR', 'Rupiah');
insert into raw_currency_tab (currency, description) values ('CNY', 'Yuan Renminbi');
insert into raw_currency_tab (currency, description) values ('RUB', 'Ruble');
insert into raw_currency_tab (currency, description) values ('PKR', 'Rupee');
