//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinishedGoodManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_ID { get; set; }
        public Nullable<System.DateTime> RequstedDate { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string ProductCategory { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> Quantity { get; set; }
    }
}
